### ISSUE TITLE
load_flow_model2 not found

### ISSUE THREAD

**Issue by m-pektas** [XLabs-AI/x-flux#11]
**Raised exception:** ImportError: cannot import name 'load_flow_model2'

load_flow_model2 function used in train_flux_lora_deepspeed.py but it is not defined in related util.py.

**Comment by Anghellia** [comment]
fixed with the commit: https://github.com/XLabs-AI/x-flux/commit/168cef121c233ec382b615dabb90be5a4c764ae5
