### ISSUE TITLE
about  controlnet's condition image

### ISSUE THREAD

**Issue by oukohou** [XLabs-AI/x-flux#121]
![x-flux-condimg](https://github.com/user-attachments/assets/47a65bdd-6fcc-4ab5-979c-b0c978ba1a4f)
just to make sure i didn't miss anything:
the condition image is directly added to the target image, is that true? seems a little different from what I learn from unet's condtion_image, could you please enlighten me why this operation? thanks

**Comment by Adenialzz** [comment]
It is add.  See controlnet papar fig. 3. After zero conv, condition $$\mathbf{c}_f$$ is added to input $$\mathbf{z}_t$$

**Comment by oukohou** [comment]
Thanks for the correction, I’ve reviewed it again, and indeed it is
