### ISSUE TITLE
Can non-square images be trained on ControlNet?

### ISSUE THREAD

**Issue by Artemis1111** [XLabs-AI/x-flux#136]
I have a few questions:

1. Is it mandatory to use 1024x1024 resolution when fine-tuning ControlNet? For example, is it possible to train using 1280x768 images?

2. Related to question 1, does ControlNet support training with various bucket resolutions?

3. Has the pre-trained ControlNet model been trained on images of diverse resolutions?

4. If the answer to question 3 is no, is the model still capable of performing inference on images with different resolutions?

**Comment by Artemis1111** [comment]
anyone please answer me ToT

**Comment by chenlijn** [comment]
Yes, it does support different resolutions, but both width and height should be divisible by 8.

**Comment by Artemis1111** [comment]
oh, thank you. Can a mixed dataset with varying image sizes still be trained in the same way?

**Comment by oukohou** [comment]
SD3's paper, section5.3 described this in detail
