### ISSUE TITLE
 Has anyone successfully created a ControlNet model?

### ISSUE THREAD

**Issue by Artemis1111** [XLabs-AI/x-flux#140]
I followed the X-Flux code to create a ControlNet model. However, when using the Canny method, it didn’t work as I intended. The generated images didn’t reflect the conditions provided by the input images.

I attempted to create a ControlNet model with the Canny preprocessor. My training dataset included 6,000 images, and I trained for approximately 30k steps. The learning rate (LR) was set to 2e-5 as provided in the initial configuration, and the image size was 1024x1024.

Even if it's not specific to Canny, I would like to know general recommendations: 

What learning rate (LR) works best, how many images are typically needed, and how many steps or epochs should I train for successful results? Any advice or insights would be greatly appreciated.

**Comment by thethanksforthegod** [comment]
tried and not working also

**Comment by Artemis1111** [comment]
I conducted experiments with various learning rates, such as 8e-1 and 3e-2, for about 1000 steps each to check if any training progress was being made. However, the resulting safetensors files are identical to the pre-training safetensors files (verified through `sha256sum`). Additionally, the inference results are completely the same as before training.

If anyone has managed to make even minimal progress with training using x-flux, I would greatly appreciate it if you could share how you achieved it. Thank you!

**Comment by Adenialzz** [comment]
How can the controlnet model be exactly the same as the pre-trained model? Which specific models do you mean?

**Comment by Artemis1111** [comment]
I created `a pretrained ControlNet model` using the `X-Flux code`. However, no training took place at all. I later discovered the cause: I was supposed to use `a transformer model` to initialize `the pretrained ControlNet`, but I mistakenly used `an FP16-saved fine-tuned transformer model`.

Although `X-Flux` anticipated such issues and provided a `mixed_precision` variable in the `test_canny_controlnet.yaml` file within the `train_configs` folder, setting this variable to `fp16` did not resolve the problem, and the loss continued to output `NaN`.

Finally, I changed the saving format of the fine-tuned transformer model to `BF16`, and I was able to successfully fine-tune `the ControlNet model` (specifically, the `Canny` model).

**Comment by saisritejakuppaEros** [comment]
@Artemis1111 , any chance have you run into the error
[rank1]: RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
[rank1]: making sure all `forward` function outputs participate in calculating loss. 
[rank1]: If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
[rank1]: Parameter indices which did not receive grad for rank 1: 54 55 56 57 58 59


if yes can you please let me know
