### ISSUE TITLE
Question About Training Loss

### ISSUE THREAD

**Issue by Hzj199** [XLabs-AI/x-flux#16]
In [FLUX](https://huggingface.co/black-forest-labs/FLUX.1-dev), it is mentioned that 'Trained using guidance distillation, making FLUX.1 [dev] more efficient.' Therefore, the output of FLUX-dev should be the result of the teacher model after CFG. Would using SD3's training loss affect this?

**Comment by bghira** [comment]
it forces the model to require cfg at sampling time, which they have added to their sampling code in x-flux
