### ISSUE TITLE
not using autocast?

### ISSUE THREAD

**Issue by bghira** [XLabs-AI/x-flux#27]
hello, i was having a look through the code today and noticed that weight_dtype is initialised but never used. the `accelerator.mixed_precision` value is used to set `args.mixed_precision` but this isn't called anywhere.

you probably have to use the context manager from Accelerate, eg. `with accelerator.autocast():`

currently, everything is in fp32, even when the user requests bf16.

**Comment by AndreRatzenberger** [comment]
DeepSpeed is handling the casting. You have to obviously set bf16 to true in your deepspeed config.

**Comment by bghira** [comment]
yes, i saw the casting of the model inputs, when i said "not used" i mean, to apply to the model at all.

**Comment by bghira** [comment]
thanks for the info. deepspeed is really bad at autocast. it does it like a bull in a china shop. so, any training problems elsewhere are unrelated to precision.
