### ISSUE TITLE
Confused about the checkpoint output files

### ISSUE THREAD

**Issue by arrowonstr** [XLabs-AI/x-flux#48]
![image](https://github.com/user-attachments/assets/303142ec-54d2-475b-b9f9-3bfe5eab59be)
the output dir contain many files
And the file "mp_rank_00_model_states.pt" is too largs(44GB)
I cannot imagine if I have 10 checkpoints
So how can I modify the code to ensure it to generate only a small lora file
and how can use the lora file to detect a image
If someone can help me with the issue i will be really grateful

**Comment by arnkmish** [comment]
Same question here. @x-labs-ai can you please help with this.

**Comment by arrowonstr** [comment]
@arnkmish  
I tried this way:
modity the code main.py line:284
```
 save_path = os.path.join(args.output_dir, f"checkpoint-{global_step}")

                    # accelerator.save_state(save_path)
                    if not os.path.exists(save_path):
                        os.makedirs(save_path)
                    unwrapped_model_state = accelerator.unwrap_model(dit).state_dict()
                    
                    torch.save({k:unwrapped_model_state[k] for k in unwrapped_model_state.keys() if '_lora' in k},os.path.join(save_path, 'lora.bin'))
```

I think ` accelerator.save_state(save_path)` is used to resume training from checkpoint
comment out the code maybe will not affect the procedure

And make sure the parameter 'resume_from_checkpoint:' have None value
```
tracker_project_name: lora_test
resume_from_checkpoint:
gradient_accumulation_steps: 2
rank: 16
```

When detecting(main.py):
modify the code main.py 105
```
# xflux_pipeline.set_lora(None, args.lora_repo_id, args.lora_name, args.lora_weight)
xflux_pipeline.set_lora(args.local_path, args.lora_repo_id, args.lora_name, args.lora_weight)
```
and specify --local_path to your lora.bin path

I think it will work

**Comment by rickbau5** [comment]
You can also convert the output `lora.bin` to a safetensors file that will work with comfy et all by using the following.
1. this script: https://huggingface.co/spaces/safetensors/convert/blob/main/convert.py, which gives you a `safetensors`. I just call [`convert_file`](https://huggingface.co/spaces/safetensors/convert/blob/main/convert.py#L181-L209) directly. Give it the path to `lora.bin` and the desired output path, e.g `lora.safetensors`
2. this script: https://huggingface.co/comfyanonymous/flux_RealismLora_converted_comfyui/blob/main/convert.py, which fixes the keys for you.

Little bit of extra work but easy enough.
