### ISSUE TITLE
How to prepare data for controlnet training

### ISSUE THREAD

**Issue by ymlab** [XLabs-AI/x-flux#58]
Is there a detailed description?

**Comment by kadirnar** [comment]
doc: https://github.com/XLabs-AI/x-flux?tab=readme-ov-file#training-dataset

Example Dataset:
https://huggingface.co/datasets/kadirnar/fluxdev_controlnet_16k

**Comment by ymlab** [comment]
@kadirnar Hi, have you successfully trained the controlnet for flux?

**Comment by kadirnar** [comment]
> @kadirnar Hi, have you successfully trained the controlnet for flux?

yes

**Comment by mashijie1028** [comment]
Hi! Thanks for your answer. Could you please provide some demo codes about the data loader of this example dataset https://huggingface.co/datasets/kadirnar/fluxdev_controlnet_16k?

**Comment by mashijie1028** [comment]
Oh! I figured it out!

Just the one-line code:
```python
from datasets import load_dataset
ds = load_dataset("kadirnar/fluxdev_controlnet_16k")
```

**Comment by Oguzhanercan** [comment]
> > @kadirnar Hi, have you successfully trained the controlnet for flux?
> 
> yes

Hi, how many samples did you use to train a controlnet and can you mention about your compute-time resources?

**Comment by kadirnar** [comment]
> > > @kadirnar Hi, have you successfully trained the controlnet for flux?
> > 
> > 
> > yes
> 
> Hi, how many samples did you use to train a controlnet and can you mention about your compute-time resources?

Yes, I trained it. However, it doesn't support multi-GPU. Therefore, I couldn't train it with a large dataset. That's why the results are not good.

**Comment by Oguzhanercan** [comment]
@kadirnar can you mention about the number of samples and compute device - time which fails in your case, I want to compare it with mine and estimate if I can scale it or not.

**Comment by kadirnar** [comment]
> @kadirnar can you mention about the number of samples and compute device - time which fails in your case, I want to compare it with mine and estimate if I can scale it or not.

- 1xA100 and 17k image.

I think they have added multi-GPU support to the diffusers library.

**Comment by Oguzhanercan** [comment]
Do you remember how many iteration did you train it :)

**Comment by Xxxy13** [comment]
> Do you remember how many iteration did you train it :)你还记得你训练了多少次迭代吗:)

hi, have you successfully trained the controlnet for flux?
