### ISSUE TITLE
I have this....(⊙o⊙)…can not use XlabsSampler...

### ISSUE THREAD

**Issue by henger5566** [XLabs-AI/x-flux#71]
**Error occurred when executing XlabsSampler:**

list index out of range

File "E:\AI\ComfyUI\execution.py", line 317, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "E:\AI\ComfyUI\execution.py", line 192, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "E:\AI\ComfyUI\execution.py", line 169, in _map_node_over_list
process_inputs(input_dict, i)
File "E:\AI\ComfyUI\execution.py", line 158, in process_inputs
results.append(getattr(obj, func)(**inputs))
File "E:\AI\ComfyUI\custom_nodes\x-flux-comfyui\nodes.py", line 344, in sampling
x = denoise(
File "E:\AI\ComfyUI\custom_nodes\x-flux-comfyui\sampling.py", line 176, in denoise
t = timesteps[t_idx]

**Comment by henger5566** [comment]
![image](https://github.com/user-attachments/assets/4a56be0e-1b1f-41a4-b44b-43ef01d48b86)
andshow this when start ComfyUI

**Comment by Anghellia** [comment]
hi. it is not related with einops
could you please send your Comfy workflow in json format?

**Comment by henger5566** [comment]
![image](https://github.com/user-attachments/assets/86aebca1-aec5-4ec8-8528-36b5b681d8ee)
[flux.json](https://github.com/user-attachments/files/16711293/flux.json)

XlabsSampler  error..

**Comment by henger5566** [comment]
![image](https://github.com/user-attachments/assets/3f33b8d4-c5cd-4284-8cd9-6a0b4782bc75)

**Comment by Anghellia** [comment]
Please use "Empty Latent Image" node, "EmptySD3LatentImage" is not correct

**Comment by henger5566** [comment]
@Anghellia---- It's true! It really worked just as you said. Thank you so much! I can't believe I didn't think of this issue. Thanks again!
