### ISSUE TITLE
How to use IP-Adapter + ControlNet

### ISSUE THREAD

**Issue by jaebbb** [XLabs-AI/x-flux#83]
### Code
`python3 main.py  --prompt "handsome guy in the city"  --ip_repo_id XLabs-AI/flux-ip-adapter --ip_name flux-ip-adapter.safetensors --device cuda --use_ip  --img_prompt assets/example_images/statue.png --control_type canny --repo_id XLabs-AI/flux-controlnet-canny-v3 --name flux-canny-controlnet-v3.safetensors --use_controlnet --image assets/example_images/canny_example2.png`

### Sample 
| IP-Adapter image                                                                                      | Controlnet image                                                                                        | Result                                                                                                |
|--------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------|
| ![statue](https://github.com/user-attachments/assets/825e7472-bc22-46a9-8210-1fb35553e31b) | ![canny_example2](https://github.com/user-attachments/assets/742fed03-f2ee-44bf-8c3f-4d4c1c011b5e) | ![result_15](https://github.com/user-attachments/assets/ddd438d9-2305-48c6-86d2-ac627cc65885) |

**Comment by Anghellia** [comment]
Hi, thank you for using our adapters!
Currently it works bad as you see (IP-adapter mix with LoRA and ControlNet). We are exploring this issue how can we fix it.
